name: lh-playground

dependencies:
    - liquid-base
    - liquid-containers
    - liquid-prelude
    - liquidhaskell

ghc-options:
    - -Wall

library:
    source-dirs: lib
    ghc-options:
        - -fno-warn-incomplete-patterns # liquidhaskell aready does this for us
        - -fplugin=LiquidHaskell
        - -fplugin-opt=LiquidHaskell:--short-names # errors are unreadable without this
